package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.64

import (
	"context"
	"fmt"
	"privacy-ex/pkg/ent"
	"privacy-ex/pkg/graph/gen"

	"entgo.io/contrib/entgql"
)

// Node is the resolver for the node field.
func (r *queryResolver) Node(ctx context.Context, id int) (ent.Noder, error) {
	panic(fmt.Errorf("not implemented: Node - node"))
}

// Nodes is the resolver for the nodes field.
func (r *queryResolver) Nodes(ctx context.Context, ids []int) (
	[]ent.Noder,
	error,
) {
	panic(fmt.Errorf("not implemented: Nodes - nodes"))
}

// Posts is the resolver for the posts field.
func (r *queryResolver) Posts(
	ctx context.Context,
	after *entgql.Cursor[int],
	first *int,
	before *entgql.Cursor[int],
	last *int,
	where *ent.PostWhereInput,
) (*ent.PostConnection, error) {
	//  기본적으로 모든 사용자가 조회 가능
	panic(fmt.Errorf("not implemented: Posts - posts"))
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(
	ctx context.Context,
	after *entgql.Cursor[int],
	first *int,
	before *entgql.Cursor[int],
	last *int,
	where *ent.UserWhereInput,
) (*ent.UserConnection, error) {
	panic(fmt.Errorf("not implemented: Users - users"))
}

// Query returns gen.QueryResolver implementation.
func (r *Resolver) Query() gen.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
